### ISSUE TITLE
Chore: Get full Functional Test env/browser matrix support.

### ISSUE THREAD

**Issue by ryan-roemer** [FormidableLabs/converter-flux#37]
Here's the wide sampling of things we want to support.
- [ ] Local (Mac)
  - [x] Chrome
  - [x] Firefox (Failed on 21.0, Passed on 35.0, 40.0.3)
  - [ ] PhantomJS (#34 - Phantom fails)
  - [ ] Safari (`Uncaught Error: com.google.gson.JsonObject cannot be cast to java.lang.String`)
- [ ] Local (Windows)
  - [ ] PhantomJS (#34 - Phantom fails)
  - [ ] Firefox
  - [ ] Chrome
  - [ ] IE
- [ ] Travis
  - [ ] PhantomJS (#34 - Phantom fails)
  - [x] Firefox
- [ ] Appveyor (#36 - Appveyor browsers fail)
  - [ ] PhantomJS (#34 - Phantom fails)
  - [ ] IE
  - [ ] Chrome
  - [ ] Firefox
- [ ] Sauce Labs
  - [ ] _A broad sampling of os/browsers_

Going with default of `local.firefox` for now for common case for Mac devs.
